# inventory.ini — generated dynamically by GitHub Actions
# This file is a static example for local testing

[web]
# Replace with actual EC2 IPs after terraform apply
 10.0.10.196 ansible_user=ec2-user-1 ansible_ssh_private_key_file=~/.ssh/ecommerce-keypair.pem
 10.0.20.90 ansible_user=ec2-user-2 ansible_ssh_private_key_file=~/.ssh/ecommerce-keypair.pem

[web:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
